<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="UTF-8">
        <title>RegisterForm</title>
    </head>
    <body>
        <h1>Connexion</h1>
        
        <form action="logic/login.php" method="POST">
        
            <div>
                <label for="email">Email :</label>
                <input type="email" name="email" id="email" required>
            </div>
        
            <div>
                <label for="password">Mot de passe :</label>
                <input type="password" name="password" id="password" required>
            </div>
        
            <div>
                <button type="submit">Se connecter</button>
            </div>
        
        </form>
    </body>
</html>