<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="UTF-8">
        <title>RegisterForm</title>
    </head>
    <body>
    <h1>Inscription</h1>
    
    <form action="logic/register.php" method="POST">
        
                
        <div>
            <label for="first_name">Prénom :</label>
            <input type="text" name="first_name" id="first_name" required>
        </div>
    
        <div>
            <label for="last_name">Nom :</label>
            <input type="text" name="last_name" id="last_name" required>
        </div>
        
        <div>
            <label for="email">Email :</label>
            <input type="email" name="email" id="email" required>
        </div>
    
        <div>
            <label for="password">Mot de passe :</label>
            <input type="password" name="password" id="password" required>
        </div>

        <div>
            <button type="submit">S'inscrire</button>
        </div>
    
    </form>
</body>
</html>